name: "SimpleCov Report"
description: "SimpleCov Report"
author: fukumone|pinnacles
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold
    default: "90"
    required: false
  resultPath:
    description: "json path"
    default: "coverage/coverage.json"
    required: false
  token:
    description: "Github token"
    required: true
  event_name:
    description: "pull_request or push"
    default: "pull_request"
    required: true
  pr_number:
    description: "Set pr_number if event_name is selected."
    required: false
  head_branch:
    description: "Compare head branch coverage results"
    required: true
runs:
  using: 'node16'
  main: "dist/index.js"
